### PR TITLE
New webapp

### PR DESCRIPTION
**Pull request by BeckySharp**
A dev page for the webapp, which allows you to enter custom rules, to develop the grammar

to use: go to `localhost:9000/dev`
then, enter a query and a rule
the rule should reference the `${query}` and the `${chunk}` just like the other rules
example:
image

### CODE REVIEW

**Comment by BeckySharp** [comment]
FYI @royakabiri (and @MihaiSurdeanu )
You can check out this branch (before we merge) and play with it, see if it meets your needs

**Comment by BeckySharp** [comment]
thanks for all the help getting it done @marcovzla !!

**Comment by royakabiri** [comment]
Thanks @BeckySharp!
I added the code to use lemmas in the queries.
I will play with the new app and will let you know how it goes!

**Review by marcovzla — APPROVED** [review]
This looks great. Thanks!

**Pull request merged**
