### PR TITLE
Showing evidence for the extractions

### PR DESCRIPTION
**Pull request by BeckySharp**
Added the ability in the `dev` page to expand a row in the results table to see the first N evidences (where N is set by `taxero.numEvidenceDisplay` in `application.conf`, default 3)

Here's what it looks like:
image

fyi @maxaalexeeva @cl4yton -- we can use this in the automates demo, but having the multiple args thing is less trivial.  I'll work on it, but I think the smartest thing for us to do would be to come up with example rules for **binary** relations of interest (i.e., can be expressed with ${query} and ${result}) for the demo

### CODE REVIEW

**Comment by BeckySharp** [comment]
FYI DocIDs are the luceneDocID

**Comment by cl4yton** [comment]
Thanks Becky! 
I'll need to some help to understand the issue about multiple args. Perhaps the three of us (@BeckySharp @maxaalexeeva ) could chat tomorrow (Wed)?

**Comment by maxaalexeeva** [comment]
Thanks @BeckySharp !

@cl4yton, some events can have multiple arguments, e.g., for the migration use case, for one migration event you could have like 6 different arguments, e.g., moveTo, moveFrom, startTime, endTime, group, etc. For most of our extractions in automates (except for IntervalParamSetting), we were using binary relations (e.g., var-def, var-unit), although we could have gone for something like var -> [def, unit, constraint] (not the real datastructure)

@BeckySharp, is that what you mean? 

I can chat tomorrow, though, except for between 1 and 3:15.

**Comment by BeckySharp** [comment]
Yes -- in a 10 min call I can explain why they're more work to add to the
existing webapp, but fwiw I've started on a diff webapp that can handle
them, but IDK when it'll be ready so this is likely the best bet for the
demo
But again, we can chat tomorrow

**Comment by marcovzla** [comment]
This looks great! Thanks!

**Pull request merged**
